FROM openjdk:17-slim

RUN apt-get update && apt-get install -y iputils-ping telnet postgresql-client && rm -rf /var/lib/apt/lists/*

COPY ../backend/target/backend-0.0.1-SNAPSHOT.jar /backend-0.0.1-SNAPSHOT.jar

CMD ["java", "-jar", "/backend-0.0.1-SNAPSHOT.jar"]
