version: '3.10'

services:
  backend-service:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
    container_name: backend-app
    ports:
      - "8081:8081"
    restart: unless-stopped

  frontend-service:
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    container_name: frontend-app
    ports:
      - "80:80"   # map container port 80 to host 3000
    restart: always
